name: "Build"

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize


env:
  BUILD_CERTIFICATE_BASE64: ${{ secrets.OSX_BUILD_CERTIFICATE_BASE64 }}
  P12_PASSWORD: ${{ secrets.OSX_P12_PASSWORD }}
  #BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
  KEYCHAIN_PASSWORD: ${{ secrets.OSX_KEYCHAIN_PASSWORD }}
  CODESIGN_CERT: ${{ secrets.OSX_CODESIGN_CERT }}
  APPLE_ID_USER: ${{ secrets.OSX_APPLE_ID_USER }}
  APPLE_ID_PASSWORD: ${{ secrets.OSX_APPLE_ID_PASSWORD }}
  APPLE_ID_PROVIDER_SHORT_NAME: ${{ secrets.OSX_APPLE_ID_PROVIDER_SHORT_NAME }}

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install the Apple certificate
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          #PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          #echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          #mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          #cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Build app
        run: ./contrib/osx/make_osx $CODESIGN_CERT
      - name: Debug
        run: |
          pwd
          ls -la
          ls -la dist
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: artifact-macos
          path: dist/*.dmg
          if-no-files-found: error
          retention-days: 7
